### ISSUE TITLE
License file?

### ISSUE THREAD

**Issue by edgan** [xtuc/acorn-import-attributes#16]
I don't see any license file. Can one added to the repository?

**Comment by HSH73** [comment]
I support the request - I see under Readme "This plugin is released under an MIT License." but I would as well appriciate a customary license file with copyright notice. Thank you.

**Comment by bodorjzsolt** [comment]
Basically the MIT conditions are impossible to fulfil without a copyright.

**Comment by xtuc** [comment]
Please feel free to add a MIT license with my name in the project

**Comment by henriksjostrom** [comment]
https://github.com/xtuc/acorn-import-attributes/pull/26
