### ISSUE TITLE
License not found for [@acorn-import-assertions 1.8.0]

### ISSUE THREAD

**Issue by RohaitKS** [xtuc/acorn-import-attributes#18]
How can I find the license file of [@acorn-import-assertions 1.8.0] . Master license is available, but I am looking for the specific these one.

**Comment by RohaitKS** [comment]
@xtuc Thankyou for your feedback but complete information is not available. I want license file for 1.8.0 version but it is not available. Please help me in this regard

**Comment by xtuc** [comment]
Added in acorn-import-attributes@1.9.2
