### ISSUE TITLE
Security: Package.json Reference To Non-NPM Package: "test262"

### ISSUE THREAD

**Issue by paulrrogers** [xtuc/acorn-import-attributes#24]
Security tools dislike references to packages not defined in the public NPM repo because of the risk someone could squat them and intercept installation attempts to inject naughty code.

Is that package still needed? Has it perhaps been renamed? ~If hosted elsewhere can that be defined in the `package.json`, at least to satisfy audits?~ [EDIT: Now I see the package source is defined, albeit implicitly via GitHub, perhaps that needs to be full URL or must be the public NPM.]

**Comment by paulrrogers** [comment]
@xtuc much thanks for merging my PR.

Any chance a new version could be tagged so that the change can work its way downstream to WebPack and others?

**Comment by xtuc** [comment]
@paulrrogers  I published acorn-import-attributes@1.9.2
