### ISSUE TITLE
allow to customize `keyword`

### ISSUE THREAD

**Issue by alexander-akait** [xtuc/acorn-import-attributes#30]
Will be great to allow setup `keyword` on different names, in webpack we need support `assert` and `with` together for compatibility, yes we can use old `acorn-import-asse` package, but there is a problem - no bugs fixes in `acorn-import-assertions`, because it was renamed

/cc @xtuc

**Comment by alexander-akait** [comment]
Try to find time on PR, but a lot of issues, right now... Also will be great to undestand `assert` or `with` keyword were used, because we need to keep code as is for external requests

**Comment by xtuc** [comment]
Published in `acorn-import-attributes@1.9.4`
