### ISSUE TITLE
Include LICENSE file in the installed node_modules

### ISSUE THREAD

**Issue by MarkAshraf96** [xtuc/acorn-import-attributes#37]
Including the LICENSE file in the node_modules to make the package compatible with with license checkers as 'license-checker' package.
Which make it easier to for other developers to check the package license.

**Comment by xtuc** [comment]
The license is here https://github.com/xtuc/acorn-import-attributes/blob/main/LICENSE

**Comment by MarkAshraf96** [comment]
Sorry, I got a bit mixed up, because we are still using the acorn-import-assertions, and back then there was no license file in the package. And when the link redirected me to here I didn't notice it's there.
